name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using your JSON secret
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build with Cloud Build
        uses: google-github-actions/cloud-build@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          substitutions: _IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/president-county-api
          config: |
            steps:
            - name: 'gcr.io/cloud-builders/docker'
              args: ['build','-t','$_IMAGE','-f','Dockerfile','.']
            - name: 'gcr.io/cloud-builders/docker'
              args: ['push','$_IMAGE']
            images: ['$_IMAGE']
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          region: ${{ secrets.GCP_REGION }}
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/president-county-api
          flags: --allow-unauthenticated --ingress=all --port=8080

      - name: Show URL
        run: echo "Service URL = ${{ steps.deploy.outputs.url }}"
