name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION:     ${{ secrets.GCP_REGION }}            # keep one region secret
  SERVICE:    ${{ secrets.CLOUD_RUN_SERVICE }}
  REPO:       cloud-run-source-deploy
  IMAGE:      ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Handy on first run; harmless later
      - name: Ensure Artifact Registry repo exists
        run: |
          gcloud artifacts repositories describe "$REPO" --location="$REGION" || \
          gcloud artifacts repositories create  "$REPO" --repository-format=docker --location="$REGION"

      - name: Build and push with Cloud Build (uses your Dockerfile)
        run: |
          gcloud builds submit \
            --project="$PROJECT_ID" \
            --tag "$IMAGE" .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --project="$PROJECT_ID" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --update-secrets GOOGLE_APPLICATION_CREDENTIALS=credentials_json:latest
