name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using your JSON secret
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build & deploy in one step using Cloud Build + Cloud Run
      # This action will use your Dockerfile to build the image.
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          region:  ${{ secrets.GCP_REGION }}
          source:  .                # build from repo root using Dockerfile
          # Optional: set min/max instances, env vars, concurrency, etc.
          flags: >
            --allow-unauthenticated
            --ingress=all
            --port=8080

      - name: Show URL
        run: echo "Service URL = ${{ steps.deploy.outputs.url }}"
